# Site
repository: mhmednisar/resume
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Nisar Ahmed
#title: 
email: ahmed.04786@gmail.com
phone: +919587991487
website: https://nisarahmed.me

# Social links
twitter_username: mahmednisar
github_username:  mahmednisar
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
instagram_username: mahmednisar
linkedin_username: mahmednisar
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Self-motivated person believes in growth and very open to new ideas. I am looking for the place where my skills and expertise is being filly utilized and proved to be an asset to the company. I am fascinatd towards continuous learning process and capable of working in a team.

# Projects Section
 projects_title: Movie-Recomender 

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
 education_title: B.Tech (Computer Science)  #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
